qsub -pe make 2 -cwd GWASscript_0.r
qsub -pe make 2 -cwd GWASscript_1.r
qsub -pe make 2 -cwd GWASscript_2.r
qsub -pe make 2 -cwd GWASscript_3.r
qsub -pe make 2 -cwd GWASscript_4.r
qsub -pe make 2 -cwd GWASscript_5.r
qsub -pe make 2 -cwd GWASscript_6.r
qsub -pe make 2 -cwd GWASscript_7.r
qsub -pe make 2 -cwd GWASscript_8.r
qsub -pe make 2 -cwd GWASscript_9.r
qsub -pe make 2 -cwd GWASscript_10.r
qsub -pe make 2 -cwd GWASscript_11.r
qsub -pe make 2 -cwd GWASscript_12.r
qsub -pe make 2 -cwd GWASscript_13.r
qsub -pe make 2 -cwd GWASscript_14.r
qsub -pe make 2 -cwd GWASscript_15.r
qsub -pe make 2 -cwd GWASscript_16.r
qsub -pe make 2 -cwd GWASscript_17.r
qsub -pe make 2 -cwd GWASscript_18.r
qsub -pe make 2 -cwd GWASscript_19.r
qsub -pe make 2 -cwd GWASscript_20.r
qsub -pe make 2 -cwd GWASscript_21.r
qsub -pe make 2 -cwd GWASscript_22.r
qsub -pe make 2 -cwd GWASscript_23.r
qsub -pe make 2 -cwd GWASscript_24.r
qsub -pe make 2 -cwd GWASscript_25.r
qsub -pe make 2 -cwd GWASscript_26.r
qsub -pe make 2 -cwd GWASscript_27.r
qsub -pe make 2 -cwd GWASscript_28.r
qsub -pe make 2 -cwd GWASscript_29.r
qsub -pe make 2 -cwd GWASscript_30.r
qsub -pe make 2 -cwd GWASscript_31.r
qsub -pe make 2 -cwd GWASscript_32.r
qsub -pe make 2 -cwd GWASscript_33.r
qsub -pe make 2 -cwd GWASscript_34.r
qsub -pe make 2 -cwd GWASscript_35.r
qsub -pe make 2 -cwd GWASscript_36.r
qsub -pe make 2 -cwd GWASscript_37.r
qsub -pe make 2 -cwd GWASscript_38.r
qsub -pe make 2 -cwd GWASscript_39.r
qsub -pe make 2 -cwd GWASscript_40.r
qsub -pe make 2 -cwd GWASscript_41.r
qsub -pe make 2 -cwd GWASscript_42.r
qsub -pe make 2 -cwd GWASscript_43.r
qsub -pe make 2 -cwd GWASscript_44.r
qsub -pe make 2 -cwd GWASscript_45.r
qsub -pe make 2 -cwd GWASscript_46.r
qsub -pe make 2 -cwd GWASscript_47.r
qsub -pe make 2 -cwd GWASscript_48.r
qsub -pe make 2 -cwd GWASscript_49.r
qsub -pe make 2 -cwd GWASscript_50.r
qsub -pe make 2 -cwd GWASscript_51.r
qsub -pe make 2 -cwd GWASscript_52.r
qsub -pe make 2 -cwd GWASscript_53.r
qsub -pe make 2 -cwd GWASscript_54.r
qsub -pe make 2 -cwd GWASscript_55.r
qsub -pe make 2 -cwd GWASscript_56.r
qsub -pe make 2 -cwd GWASscript_57.r
qsub -pe make 2 -cwd GWASscript_58.r
qsub -pe make 2 -cwd GWASscript_59.r
qsub -pe make 2 -cwd GWASscript_60.r
qsub -pe make 2 -cwd GWASscript_61.r
qsub -pe make 2 -cwd GWASscript_62.r
qsub -pe make 2 -cwd GWASscript_63.r
qsub -pe make 2 -cwd GWASscript_64.r
qsub -pe make 2 -cwd GWASscript_65.r
qsub -pe make 2 -cwd GWASscript_66.r
qsub -pe make 2 -cwd GWASscript_67.r
qsub -pe make 2 -cwd GWASscript_68.r
qsub -pe make 2 -cwd GWASscript_69.r
qsub -pe make 2 -cwd GWASscript_70.r
qsub -pe make 2 -cwd GWASscript_71.r
qsub -pe make 2 -cwd GWASscript_72.r
qsub -pe make 2 -cwd GWASscript_73.r
qsub -pe make 2 -cwd GWASscript_74.r
qsub -pe make 2 -cwd GWASscript_75.r
qsub -pe make 2 -cwd GWASscript_76.r
qsub -pe make 2 -cwd GWASscript_77.r
qsub -pe make 2 -cwd GWASscript_78.r
qsub -pe make 2 -cwd GWASscript_79.r
qsub -pe make 2 -cwd GWASscript_80.r
qsub -pe make 2 -cwd GWASscript_81.r
qsub -pe make 2 -cwd GWASscript_82.r
qsub -pe make 2 -cwd GWASscript_83.r
qsub -pe make 2 -cwd GWASscript_84.r
qsub -pe make 2 -cwd GWASscript_85.r
qsub -pe make 2 -cwd GWASscript_86.r
qsub -pe make 2 -cwd GWASscript_87.r
qsub -pe make 2 -cwd GWASscript_88.r
qsub -pe make 2 -cwd GWASscript_89.r
qsub -pe make 2 -cwd GWASscript_90.r
qsub -pe make 2 -cwd GWASscript_91.r
qsub -pe make 2 -cwd GWASscript_92.r
qsub -pe make 2 -cwd GWASscript_93.r
qsub -pe make 2 -cwd GWASscript_94.r
qsub -pe make 2 -cwd GWASscript_95.r
qsub -pe make 2 -cwd GWASscript_96.r
qsub -pe make 2 -cwd GWASscript_97.r
qsub -pe make 2 -cwd GWASscript_98.r
qsub -pe make 2 -cwd GWASscript_99.r
qsub -pe make 2 -cwd GWASscript_100.r
qsub -pe make 2 -cwd GWASscript_101.r
qsub -pe make 2 -cwd GWASscript_102.r
qsub -pe make 2 -cwd GWASscript_103.r
qsub -pe make 2 -cwd GWASscript_104.r
qsub -pe make 2 -cwd GWASscript_105.r
qsub -pe make 2 -cwd GWASscript_106.r
qsub -pe make 2 -cwd GWASscript_107.r
qsub -pe make 2 -cwd GWASscript_108.r
qsub -pe make 2 -cwd GWASscript_109.r
qsub -pe make 2 -cwd GWASscript_110.r
qsub -pe make 2 -cwd GWASscript_111.r
qsub -pe make 2 -cwd GWASscript_112.r
qsub -pe make 2 -cwd GWASscript_113.r
qsub -pe make 2 -cwd GWASscript_114.r
qsub -pe make 2 -cwd GWASscript_115.r
qsub -pe make 2 -cwd GWASscript_116.r
qsub -pe make 2 -cwd GWASscript_117.r
qsub -pe make 2 -cwd GWASscript_118.r
qsub -pe make 2 -cwd GWASscript_119.r
qsub -pe make 2 -cwd GWASscript_120.r
qsub -pe make 2 -cwd GWASscript_121.r
qsub -pe make 2 -cwd GWASscript_122.r
qsub -pe make 2 -cwd GWASscript_123.r
qsub -pe make 2 -cwd GWASscript_124.r
qsub -pe make 2 -cwd GWASscript_125.r
qsub -pe make 2 -cwd GWASscript_126.r
qsub -pe make 2 -cwd GWASscript_127.r
qsub -pe make 2 -cwd GWASscript_128.r
qsub -pe make 2 -cwd GWASscript_129.r
qsub -pe make 2 -cwd GWASscript_130.r
qsub -pe make 2 -cwd GWASscript_131.r
qsub -pe make 2 -cwd GWASscript_132.r
qsub -pe make 2 -cwd GWASscript_133.r
qsub -pe make 2 -cwd GWASscript_134.r
qsub -pe make 2 -cwd GWASscript_135.r
qsub -pe make 2 -cwd GWASscript_136.r
qsub -pe make 2 -cwd GWASscript_137.r
qsub -pe make 2 -cwd GWASscript_138.r
qsub -pe make 2 -cwd GWASscript_139.r
qsub -pe make 2 -cwd GWASscript_140.r
qsub -pe make 2 -cwd GWASscript_141.r
qsub -pe make 2 -cwd GWASscript_142.r
qsub -pe make 2 -cwd GWASscript_143.r
qsub -pe make 2 -cwd GWASscript_144.r
qsub -pe make 2 -cwd GWASscript_145.r
qsub -pe make 2 -cwd GWASscript_146.r
qsub -pe make 2 -cwd GWASscript_147.r
qsub -pe make 2 -cwd GWASscript_148.r
qsub -pe make 2 -cwd GWASscript_149.r
qsub -pe make 2 -cwd GWASscript_150.r
qsub -pe make 2 -cwd GWASscript_151.r
